change json to mongoose
AlonaMaliarchyk/nodejs-REST-API-app pull request #2
Opened 2023-04-17 15:52 UTC by AlonaMaliarchyk

2023-04-17 18:29 UTC, KhYulian commented on controllers/contactsController.js
> +        const oneContact = await Contact.findOne({contactId: ObjectId});
```suggestion
        const contact = await Contact.findOne({_id: contactId });
```

2023-04-17 18:30 UTC, KhYulian commented on controllers/contactsController.js
> +        const {_id} = req.params;
```suggestion
        const {contactId} = req.params;
```

2023-04-17 18:31 UTC, KhYulian commented on models/contact.js
> +})
Схеми Joi виносьте в окремий файл. e.g. utils/validation/contactValidationSchemas.js

2023-04-17 18:32 UTC, KhYulian commented on utils/ctrlWrapper.js
> +    return func;
```suggestion
    return async(req, res, next)=>{
        try {
            await ctrl(req, res, next);
        } catch (error) {
            next(error);
        }
    }    
```

2023-04-17 18:32 UTC, KhYulian commented on utils/validateBody.js
> +            next(HttpError(404, error.message));
```suggestion
          return  next(HttpError(404, error.message));
```

2023-04-17 18:32 UTC, KhYulian requested changes
Потрібні правки

2023-04-17 19:07 UTC, AlonaMaliarchyk commented on controllers/contactsController.js
> +        const {_id} = req.params;
done!

2023-04-17 19:08 UTC, AlonaMaliarchyk commented on controllers/contactsController.js
> +        const oneContact = await Contact.findOne({contactId: ObjectId});
done

2023-04-17 19:36 UTC, AlonaMaliarchyk commented on models/contact.js
> +})
done

2023-04-17 19:37 UTC, AlonaMaliarchyk commented on models/contact.js
> +})
Але  ментор казав внести в 1 файл зі схемою,щоб точно не забути внести зміни,коли це буде потрібно

2023-04-17 19:40 UTC, AlonaMaliarchyk commented on utils/ctrlWrapper.js
> +    return func;
done

2023-04-17 19:42 UTC, AlonaMaliarchyk commented on utils/validateBody.js
> +            next(HttpError(404, error.message));
done

2023-04-18 08:05 UTC, KhYulian commented on models/contact.js
> +})
схеми монгус та схеми joi - це зовсім різні речі, їх не слід змішувати

2023-04-18 08:06 UTC, KhYulian approved these changes
Чудова робота ❤️

2023-04-18 08:06 UTC, merged